# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf


In [2]:
tf.__version__

'2.1.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
dataset = pd.read_csv('Folds5x2_pp.csv')
dataset.head()

AT      V       AP     RH      PE
0   8.34  40.77  1010.84  90.01  480.48
1  23.64  58.49  1011.40  74.20  445.75
2  29.74  56.90  1007.15  41.91  438.76
3  19.07  49.69  1007.22  76.79  453.09
4  11.80  40.66  1017.13  97.20  464.43

In [4]:
x = dataset.iloc[:, :-1].values

In [5]:
print(x)

[[   8.34   40.77 1010.84   90.01]
 [  23.64   58.49 1011.4    74.2 ]
 [  29.74   56.9  1007.15   41.91]
 ...
 [  15.99   43.34 1014.2    78.66]
 [  17.65   59.87 1018.58   94.65]
 [  23.68   51.3  1011.86   71.24]]


In [6]:
y = dataset.iloc[:, -1].values

### Splitting the dataset into the Training set and Test set

In [7]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

## Part 2 - Building the ANN

### Initializing the ANN

In [8]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [9]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the second hidden layer

In [10]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the output layer

In [11]:
ann.add(tf.keras.layers.Dense(units = 1))

## Part 3 - Training the ANN

### Compiling the ANN

In [12]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN on the Training set

In [13]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Train on 7654 samples
Epoch 1/100
7654/7654 [==============================] - 1s 153us/sample - loss: 219647.0824
Epoch 2/100
7654/7654 [==============================] - 0s 63us/sample - loss: 12947.1270
Epoch 3/100
7654/7654 [==============================] - 1s 66us/sample - loss: 540.5552
Epoch 4/100
7654/7654 [==============================] - 0s 64us/sample - loss: 424.5865
Epoch 5/100
7654/7654 [==============================] - 0s 65us/sample - loss: 342.6875
Epoch 6/100
7654/7654 [==============================] - 0s 65us/sample - loss: 273.6540
Epoch 7/100
7654/7654 [==============================] - 0s 65us/sample - loss: 214.44790s - loss:
Epoch 8/100
7654/7654 [==============================] - 0s 64us/sample - loss: 163.3597
Epoch 9/100
7654/7654 [==============================] - 0s 65us/sample - loss: 124.7978
Epoch 10/100
7654/7654 [==============================] - 0s 64us/sample - loss: 95.1910
Epoch 11/100
7654/7654 [==============================] - 1s 66us/sample

## Part 4 - Making the predictions and evaluating the model

### Predicting the Test set results

In [16]:
y_pred = ann.predict(x_test)
np.set_printoptions(precision = 2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[431.43 426.18]
 [450.8  451.1 ]
 [446.27 442.87]
 ...
 [457.29 454.2 ]
 [450.35 444.13]
 [432.64 436.58]]


### Making the Confusion Matrix

In [17]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9074200573800671